runtime: php72
#api_version: 1



handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: imagenes

- /index.html
  static_files: index.php
  upload: index\.php

- url: .*
  script: auto

