runtime: php72
#api_version: 1



handlers:
- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /img
  static_dir: imagenes
  
- url: /stylesheets
  static_dir: stylesheets

- url: /(.*\.php)
  static_files: \1
  upload: index.index

- url: .*
  script: auto

