
runtime: php72


handlers:
- url: /favicon\.ico
  static_files: imagenes/FYHIcono.png
  upload: imagenes/favicon\.icon

- url: /stylesheets
  static_dir: /stylesheets

- url: /imagenes
  static_dir: imagenes

- url: .*
  script: auto

