runtime: php72
#api_version: 1



handlers:
- url: /web
  static_dir: css

- url: /js
  static_dir: js

- url: /imagenes
  static_dir: imagenes
  
- url: /stylesheets
  static_dir: stylesheets
  
- url: /web
  static_dir: js

- url: /(.*\.php)
  static_files: \1
  upload: index.index

- url: .*
  script: auto

