
runtime: php72


handlers:
- url: /favicon\.ico
  static_files: imagenes/FYHIcono.png
  upload: imagenes/favicon\.icon

- url: /css/bootstrap
  static_dir: web/css

- url: /js/bootstrap
  static_dir: web/js

- url: /imagenes
  static_dir: imagenes

- url: .*
  script: auto

