
runtime: php72


handlers:
- url: /favicon\.ico
  static_files: imagenes/FYHIcono.png
  upload: imagenes/favicon\.icon

- url: /stylesheets
  static_dir: /stylesheets


- url: /css
  static_dir: web/css


- url: /css/bootstrap
  static_dir: web/css/bootstrap


- url: /js
  static_dir: web/js


- url: /js
  static_dir: web/js


- url: /imagenes
  static_dir: imagenes

- url: .*
  script: auto

